flats/urls.py
from django.urls import path
from flats.views import flat_list_view

app_name = 'flats'

urlpatterns = [path("",flat_list_view, name="list"),
               ]

flats_sale/urls.py
from django.urls import path

from flats_sale.views import SaleListView #sale_id_view

app_name = "flats_sale"
urlpatterns = [
    path('sale/', SaleListView.as_view(), name = "sale"),
    #path("sale/<int:pk>", sale_id_view, name="flat"),
]

realtor_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flats/", include("flats.urls", namespace="flats")),
    path('about/', include('siteinfo.urls', namespace='info')),
    path('sale/', include('flats_sale.urls', namespace='sale')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

siteinfo/urls.py
from django.urls import path

from siteinfo.views import main_view, about_view

app_name = "siteinfo"
urlpatterns = [
    path('main/', main_view, name = "main"),
    path('about/', about_view, name = "about"),
]

comment/models.py
from django.db import models


class Comment(models.Model):
    text = models.TextField(blank=False) #нельзя отправлять пустой комментарий
    date_of_create = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=32)
    published = models.BooleanField(default=False) #премодерация

    def __str__(self):
        return self.text [ :32] + '...'
    
    class Meta:
        ordering = ('-date_of_create', )

flats_sale/models.py
from django.db import models


class Object(models.Model):
    name=models.CharField(max_length=128, verbose_name="Название")
    text=models.TextField(blank=False, verbose_name="Описание")
    location=models.CharField(max_length=128, verbose_name="Расположение")
    
class Category(models.Model):
    name=models.CharField(max_length=128, verbose_name="Название")
    
class Flat(models.Model):
    name=models.CharField(max_length=128, verbose_name="Название")
    text=models.TextField(blank=False, verbose_name="Описание")
    img=models.ImageField(upload_to="%Y/%m/%d/", verbose_name="Изображение")

siteinfo/models.py
from django.db import models

# Create your models here.

comment/forms.py
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('date_of_create','published','post')

flats_sale/forms.py
from django import forms

class FlatSearchForm(forms.Form):
    search = forms.CharField(max_length = 128)

comment/views.py
from django.shortcuts import render

# Create your views here.

flats/views.py
from django.shortcuts import render

def flat_list_view(request):
    context={"flats_list": "flats"}
    return render(request, "flats/flats_list.html",context)

flats_sale/views.py
from django.shortcuts import render #get_object_or_404
from flats_sale.models import Flat
from django.views.generic import ListView
from flats_sale.forms import FlatSearchForm
#from comment.forms import CommentForm
#from comment.models import Comment


class SaleListView(ListView):
    model = Flat
    context_object_name = 'flats_sale'
    template_name = 'flats_sale/flats_sale.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = FlatSearchForm()         
        return context                          

    def get(self, request, *args, **kwargs):
        
        form = FlatSearchForm(self.request.GET)
        if form.is_valid():
           cd = form.cleaned_data  
           flats = self.model.objects.filter(name__icontains=cd['search'])
        else:    
            flats = self.model.objects.all()
        return render(request, self.template_name, self.get_context_data(object_list=flats))

siteinfo/views.py
from django.shortcuts import render

def main_view(request):
    context = {"page": "main"}
    return render(request, 'siteinfo/main.html', context)

def about_view(request):
    context = {"page": "about"}
    return render(request, 'siteinfo/about.html', context)

flats/templates/flats/flats_list.html
{% extends "root.html" %}
{% block content %}
<style>
.card-img-top {
    width: 100%;
    height: 20vw;
    object-fit: cover;
}
</style>
<div class="text d-flex justify-content-center flex-column mt-5">
    <h1 class="d-flex justify-content-center">Купить квартиру в Санкт-Петербурге</h1>
    <p class="" style="text-align: center">Поможем купить квартиру в новостройке по выгодной цене – агентство «Новые горизонты» гарантирует профессиональный подход, юридическую чистоту и финансовую безопасность сделки.</p>
</div>
<a class="nav-link text-dark" href="{% url 'sale:sale' %}">
<div class="d-flex justify-content-evenly m-2">
<div class="card" style="width: 30rem;">
  <img src="/media/4.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Новостройки</h5>
  </div>
</div>
</a>
<div class="card" style="width: 30rem;">
  <img src="/media/5.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Вторичный рынок</h5>
  </div>
</div>
</div>

{% endblock %}

flats_sale/templates/flats_sale/flats_detail.html
{% extends "root.html" %}
{% block content %}
<div class="ms-4 me-4">
    <h1>{{ pk.name }}</h1>
    <img src="{{ pk.image.url }}" alt="" width="200px" height="300px">
    <p>{{ pk.description }}</p>
</div>
    
{% endblock %}

flats_sale/templates/flats_sale/flats_sale.html
{% extends "root.html" %}
{% block content %}
<style>
.card-img-top {
    width: 100%;
    height: 20vw;
    object-fit: cover;
}
</style>
<div class="text d-flex justify-content-center flex-column mt-5">
    <h1 class="d-flex justify-content-center">Купить новую квартиру в Санкт-Петербурге</h1>
    <p class="" style="text-align: center">Поможем купить квартиру в новостройке по выгодной цене – агентство «Новые горизонты» гарантирует профессиональный подход, юридическую чистоту и финансовую безопасность сделки.</p>
    <h3 class="d-flex justify-content-center mt-5">Каталог новостроек</h3>
</div>
<form action="." method="get">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Найти" class="btn btn-success">
</form>
<div class="d-flex justify-content-evenly">
{% for flat in flats_sale %}

<div class="d-flex flex-row">
    <div class="content d-flex justify-content-evenly">
        <div class="card" style="width: 18rem;">
            <img src={{ flat.img.url }} class="card-img-top" alt="...">
            <div class="card-body d-flex flex-column align-items-start justify-content-between">
                <h5 class="card-title">{{ flat.name }}</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">От 4 200 000 ₽</h6>
                <p class="card-text">{{ flat.text }}</p>
                <a href="{% url 'sale:flat' flat.pk%}" class="btn btn-primary">Подробнее</a>
            </div>
        </div>
    </div>
</div>

{% endfor %}
</div>
{% endblock %}

siteinfo/templates/siteinfo/about.html
{% extends "root.html" %}
{% block content %}
<p>О КОМПАНИИ!</p>
{% endblock %}

siteinfo/templates/siteinfo/main.html
{% extends "root.html" %}
{% block content %}

<style>

.carousel-inner{
  height: 600px !important;
  margin: 0 auto;
}
.carousel-inner img {
  height: 700px !important;
}
h5{
    font-size: 58px;
}
p {
 font-size: 50px;
}
.card-img-overlay{
 height: 600px !important;
 margin: 0 auto;
}
.card {
    transition: 1s; /* Время эффекта */
   }
.card:hover {
    transform: scale(1.1); /* Увеличиваем масштаб */
   }
div#txt {

position: relative;

}
.txt {

position: absolute;

top: 50%;

left: 65px;

text-transform: uppercase;

color: white;

width: 350px;

background: #00000094;

padding: 10px;

text-align: center;

font: bold 24px/34px Helvetica, Sans-Serif;

}
</style>
<div class="w-auto d-flex flex-column justify-content-center">
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/media/6.jpg" class="d-block w-100" alt="..." style="filter: brightness(40%)">
      <div class="carousel-caption position-absolute bottom-50 end-50"">
        <h5>АН "Новые горизонты"</h5>
        <p class="fs-3">Осуществляет все операции с недвижимостью более 20 лет</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/media/7.jpg" class="d-block w-100" alt="..." style="filter: brightness(40%)">
      <div class="carousel-caption position-absolute bottom-50 end-50"">
        <h5>АН "Новые горизонты"</h5>
        <p class="fs-3">Осуществляет все операции с недвижимостью более 20 лет</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/media/8.jpg" class="d-block w-100" alt="..." style="filter: brightness(40%)">
      <div class="carousel-caption position-absolute bottom-50 end-50"">
        <h5>АН "Новые горизонты"</h5>
        <p class="fs-3">Осуществляет все операции с недвижимостью более 20 лет</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="gallery-inner container py-lg-0 py-3 mt-5 d-flex justify-content-center">
      <div class="row stats-con pb-lg-3 d-flex justify-content-beetwen">
        <div class="col-lg-4 col-6">
          <p class="counter" style="color: #5F9EA0">20</p>
          <h4>Лет на рынке</h4>
        </div>
        <div class="col-lg-4 col-6">
          <p class="counter" style="color: #5F9EA0">1698</p>
          <h4>Сделок с недвижимостью</h4>
        </div>
        <div class="col-lg-4 col-6">
          <p class="counter" style="color: #5F9EA0">2800</p>
          <h4>Обращений из разных городов</h4>
        </div>
    </div>
</div>

<div class="w-100 h-100 mt-5 d-flex justify-content-around">
<a class="nav-link text-dark" href="{% url 'flats:list' %}">
<div class="card" style="width: 18rem;">
  <img src="/media/10.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-text">Покупка недвижимости</h3>
    <p class="fs-5">Быстро, понятно, без "подводных камней"</p>
  </div>
</div>
</a>
<div class="card" style="width: 18rem;">
  <img src="/media/12.jpeg" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-text">Вторичный рынок</h3>
    <p class="fs-5">Быстро и выгодно продать квартиру</p>
  </div>
</div>
<a class="nav-link text-dark" href="{% url 'sale:sale' %}">
<div class="card" style="width: 18rem;">
  <img src="/media/11.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h3 class="card-text">Новострой</h3>
    <p class="fs-5">Выбираем квартиру в новостройке</p>
  </div>
</div>
</a>
</div>


{% endblock %}

templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Realtor</title>
        <script src = "{% static 'js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body style="height: 100%; background-color: #ffffff">
        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #5F9EA0;">
          <div class="container-fluid">
            <a class="navbar-brand text-light" href="#">NewHorizons</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active text-light" aria-current="page" href="{% url 'info:main' %}">Главная</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-light" href="{% url 'flats:list' %}">Купить квартиру</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-light" href="#">Продать квартиру</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-light" href="{% url 'info:about' %}">О нас</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-light" href="#">Контакты</a>
                </li>
              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Поиск</button>
              </form>
            </div>
          </div>
        </nav>
            {% block content %}
            {% endblock %}
    </body>
</html>